#!/usr/bin/env python3

# Usage:
# Add the CherryPy dependency. Documentation here: https://cherrypy.dev/
# Add the Mistune dependency. Documentation here:
# https://github.com/lepture/mistune
# And then run the program with python3
# $ python3 mdv <filename.md>
# Then visit http://127.0.0.1:8282/
# Note the port number and listen address are hard coded. Check the main()
# function to change them.
#
# Origin: https://github.com/jyfletcher/markdownviewer
# 
# Copyright (C) 2024 Justin Yates Fletcher
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

import cherrypy
import mistune
import sys

class Root(object):

    def __init__(self, fname):
        self.fname = fname

    @cherrypy.expose
    def index(self):
        f = open(self.fname, "r")
        d = f.read()
        f.close()
        return mistune.html(d)

def main(fname):
    cherrypy.server.socket_host = '127.0.0.1'
    cherrypy.server.socket_port = 8282
    cherrypy.quickstart(Root(fname))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: mdv <filename>")
        sys.exit(1)
    fname = sys.argv[1]
    main(fname)
